[option]
prefix_label = "_"

[textrules]
style_directives = true
style_semicolon = true

[syntaxrules]
style_indent = true
style_keyword_indent = true
style_keyword_0or1space = true
style_keyword_1or2space = true
style_keyword_1space = true
style_keyword_construct = true
style_keyword_datatype = true
style_keyword_end = true
style_keyword_maybelabel = true
style_keyword_new = true
style_keyword_newline = true
style_operator_arithmetic = true
style_operator_boolean = true
style_operator_integer = true
style_operator_unary = true
style_trailingwhitespace = true
tab_character = true
action_block_with_side_effect = true
blocking_assignment_in_always_ff = true
blocking_assignment_in_always_latch = true
case_default = true
default_nettype_none = true
enum_with_type = true
eventlist_comma_always_ff = true
explicit_case_default = true
function_same_as_system_function = true
function_with_automatic = true
genvar_declaration_in_loop = true
inout_with_tri = true
input_with_var = true
interface_port_with_modport = true
keyword_forbidden_always = true
keyword_forbidden_generate = true
keyword_forbidden_priority = true
keyword_forbidden_unique = true
keyword_forbidden_unique0 = true
keyword_forbidden_wire_reg = true
level_sensitive_always = true
localparam_explicit_type = true
localparam_type_twostate = true
loop_statement_in_always_comb = true
loop_statement_in_always_ff = true
loop_statement_in_always_latch = true
loop_variable_declaration = true
multiline_for_begin = true
multiline_if_begin = true
non_ansi_module = true
non_blocking_assignment_in_always_comb = true
operator_case_equality = true
output_with_var = true
parameter_default_value = true
parameter_explicit_type = true
parameter_in_generate = true
parameter_in_package = true
parameter_type_twostate = true
sequential_block_in_always_comb = true
sequential_block_in_always_ff = true
sequential_block_in_always_latch = true
uppercamelcase_interface = true
uppercamelcase_module = true
lowercamelcase_package = true
